Feature/jg 11 criar servidor http e conexao com banco
Jovens-Gafanhotos/crispy-fortnight pull request #1
Opened 2022-05-10 01:46 UTC by BrenoHaraujo2503

- [x] Criar configuração do typescript
- [x] Iniciar servidor com express
- [x] Configurar o banco de dados com https://prisma.io/
- [x] Configurar DOTENV

2022-05-10 21:58 UTC, fmcalado requested changes
Algumas modificações são necessárias somente para manter boas práticas de programação em time

2022-05-10 21:58 UTC, fmcalado commented on .gitignore
> +yarn.lock
Favor remover yarn.lock e package-lock.json do .gitignore, esses arquivos são essenciais para que as versões das bibliotecas sejam compatíveis e iguais em todas as máquinas.

2022-05-10 21:58 UTC, fmcalado commented on prisma/schema.prisma
> +  provider = "sqlite"
Seria bom utilizar postgres ao inves de sqlite. A capacidade de escalabilidade e segurança do PostGreSQL é muito maior do que do sqlite.

2022-05-10 21:58 UTC, fmcalado commented on .env.example
> +DATABASE_URL=""
Colocar uma linha em branco no final de todos arquivos, e remover aspas do `DATABASE_URL`

2022-05-10 21:58 UTC, fmcalado commented on tsconfig.json
> +  "compilerOptions": {
Limpar tsConfig, deixar somente propriedades que estão ativadas. É necessário manter os arquivos sempre legíveis e de facil entendimento.

2022-05-11 01:26 UTC, fmcalado approved these changes, later dismissed
All gucci

2022-05-11 22:00 UTC, miguel5g requested changes

2022-05-11 22:00 UTC, miguel5g commented on src/prisma/client.ts
> +})
Faltando uma linha em branco no final do arquivo.

2022-05-11 22:00 UTC, miguel5g commented on src/server.ts
> +});
Faltando uma linha em branco no final do arquivo.

2022-05-12 18:33 UTC, miguel5g approved these changes

2022-05-13 16:09 UTC, merged