Fix typescript error where method was required
Jovens-Gafanhotos/crispy-fortnight pull request #15
Opened 2022-07-15 03:06 UTC by BrenoHaraujo2503

2022-07-15 03:08 UTC, BrenoHaraujo2503 commented
#14

2022-07-15 19:59 UTC, miguel5g requested changes
Como citei na conversa dentro do arquivo, acredito que mudar a interface não seja a melhor alternativa. Como sugestão, acredito que uma alternativa melhor é dentro do teste criar um cast, apenas para o TypeScript aceitar.

2022-07-15 19:59 UTC, miguel5g commented on src/repositories/message-repository.ts
> +  findMany?(where: MessageFindWhere): Promise<MessageEntity[]>;
Eu não acho que modificar a interface de contrato seja a melhor alternativa, já que ela que garante o bom funcionamento e existência dos métodos necessários.

2022-07-17 16:49 UTC, miguel5g approved these changes

2022-07-17 18:19 UTC, merged