Feat/adding send mailer adapter
Jovens-Gafanhotos/crispy-fortnight pull request #17
Opened 2022-07-21 21:40 UTC by BrenoHaraujo2503

- [ ] Criar testes de envio de email

2022-07-21 22:07 UTC, miguel5g commented on src/adapters/nodemailer/nodemailer-mail-adapter.ts
> +});
Poderia mover tudo isso para uma factory? Acredito que é uma alternativa mais escalável  e testável.

2022-07-21 23:17 UTC, miguel5g requested changes

2022-07-21 23:17 UTC, miguel5g commented on src/factories/mail-transport-factory.ts
> +export function mailTransportFactory(data: MailTransportFactoryData): Transporter {
Acredito que trocar o nome da interface para `TransporterOptions` além de deixar mais intuitivo fica mais curto.

```suggestion
interface TransporterOptions {
  host?: string;
  port?: number;
  secure?: boolean;
  auth?: {
    user?: string;
    pass?: string;
  }
}

export function mailTransportFactory(data: TransporterOptions): Transporter {
```

2022-07-22 16:36 UTC, miguel5g reviewed
Agora só falta os testes, correto?

2022-07-22 16:38 UTC, BrenoHaraujo2503 commented
> Agora só falta os testes, correto?

sim

2022-07-22 23:32 UTC, BrenoHaraujo2503 commented on src/adapters/nodemailer/nodemailer-mail-adapter.spec.ts
> +  });
Essa parte está repetida

2022-07-22 23:42 UTC, miguel5g approved these changes

2022-07-22 23:42 UTC, merged